### ISSUE TITLE
Selection should be moved to the next line after inserting a horizontal rule

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-horizontal-rule#3]
Two reasons:

* It doesn't make sense to select the HR. There's simply no use for that.
* There's a problem when you insert a HR at the end of the document (see https://github.com/ckeditor/ckeditor5/issues/407) that you may not know how to insert a paragraph after it. You can actually do that by pressing <kbd>Enter</kbd> but if we insert that paragraph automatically this will be better.

**Comment by Reinmar** [comment]
PS. Just use CKEditor 4 as an example.

**Comment by pomek** [comment]
There are a few cases that need to be cover:
1. Inserting `<hr>` inside a paragraph.
    ```html
    <paragraph>Foo[]Bar</paragraph>
    =>
    <paragraph>Foo</paragraph><horizontalRule></horizontalRule><paragraph>[]Bar</paragraph>
    ```

1. Inserting `<hr>` at the end of a paragraph:
    ```html
    <paragraph>Foo[]</paragraph>
    => 
    <paragraph>Foo</paragraph><horizontalRule></horizontalRule><paragraph>[]</paragraph>
    ```

1. A paragraph cannot be a child of $root:
  An edge case but it must be covered. In empty model, insert a horizontal rule => `[<horizontalRule></horizontalRule>]`. 

1. An object (or limit) element is next to a paragraph:

    ```html
    <paragraph>Foo[]</paragraph><object>...</object>
    ```

    What should we do?
    - KISS - insert a pragraph after `<hr>`:
        ```html
        <paragraph>Foo</paragraph><horizontalRule></horizontalRule><paragraph>[]</paragraph><object>...</object>
        ```
    - find first element that allows `$text` in `<object>`. I am not sure is that even a correct solution, though. What if we don't find the element.

**Comment by Reinmar** [comment]
1. OK
2. OK
3. OK
4. Insert a new paragraph

But there are also a couple more cases that you need to cover:

* `<h1>foo[]</h1><p>xxx</p>`
* `<h1>foo[]</h1>`
* `<h1>foo[]bar</h1>`
* etc.

When in doubt, check CKE4.

**Comment by Reinmar** [comment]
Oh, and one more:

`<p>[]</p>`
