### ISSUE TITLE
Rethink the icon

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-horizontal-rule#4]
As per @oleq's request.

**Comment by dkonopka** [comment]
As I understand correctly, @oleq was concerned about the simplicity of this icon & confusing users in discoverability (it is a separator, a horizontal rule or whatever).

To be honest, I had a similar feeling choosing a `<hr>` icon, but research convinced me that we should keep it simple as much as possible (let's see GDocs/Word/other "competitors").

I can try to improve this icon a bit (as @oleq suggested) by adding a pseudo text before/after hr with opacity. Still, it might be a conflict with a page break icon in the future I guess. WDYT?

**Comment by oleq** [comment]
After some talks on Slack we decided that the current look is OK because it matches other editors on the market. If users are familiar with it, then there is no need to change it.
